name: HybridWebView PR Build
on:
  - pull_request
  - workflow_dispatch

jobs:
  call-build-workflow:
    uses: ./.github/workflows/_build.yml
    with:
      publish-packages: false
      nuget-org-push: false
