name: HybridWebView main Build
on:
  push:
    branches:
      - main

jobs:
  call-build-workflow:
    uses: ./.github/workflows/_build.yml
    with:
      publish-packages: true
      nuget-org-push: false
